startDelaySeconds: 0
hostPort: 127.0.0.1:9010
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1234/jmxrmi
ssl: false
<<<<<<< HEAD
lowercaseOutputName: false
=======
lowercaseOutputName: false
>>>>>>> ad22de67b6df0b7b679a085c0510e30ec7e2f3c6
